export const FETCH_PET_DATA_START = 'FETCH_PET_DATA_START';
export const FETCH_PET_DATA_COMPLETE = 'FETCH_PET_DATA_COMPLETE';
export const FETCH_PET_DATA_ERROR = 'FETCH_PET_DATA_ERROR';
export const GET_PET_DESC = "GET_PET_DESC";